### ISSUE TITLE
Why isn't [[AlreadyResovled]] part of the state of a promise?

### ISSUE THREAD

**Issue by allenwb** [domenic/promises-unwrapping#103]
With the January consensus rewrite, a promise's Resolve and Reject functions share [[AlreadyResolved]] resolved state in a separate record.  They also each capture a reference to their shared promise.  Why can't [[AlreadyResolved]] be internal state of the promise object?

**Comment by domenic** [comment]
This was my first approach (under the name [[PromiseFate]]), but the tests failed badly. The reason is that you actually need a stack of these.

Consider multiple reclusive calls to Promise Resolve Functions (in a universe where instead of each function having its own [[AlreadyResolved]] shared with its counterpart Promise Reject Function, it instead used an [[AlreadyResolved]] common on the promise object). You call a Promise Resolve Function, which sets [[AlreadyResolved]] to true in order to avoid allowing its counterpart Promise Reject Function to be called. The resolution is a thenable, so it ends up needing to recurse. A new Promise Resolve Function is generated and passed to the thenable's `then` method, and eventually called with a value (say `5`). But when this new Promise Resolve Function is called, it immediately sees that, oh, oops, [[AlreadyResolved]] is already set! I have to bail out and not actually set the value! Thus resolving promises with thenables (including other promises) no longer works, and many of the tests fail.
