### ISSUE TITLE
Remove race() method

### ISSUE THREAD

**Issue by mounirlamouri** [domenic/promises-unwrapping#29]
It seems that the `any()` static method from the DOM Promise has been replaced by `race()` which is basically the same behaviour with a different name.

The change has been made following the discussion in issue #13. Basically, the problem being that `any()` was confusing because it might mean "as soon as one promise settle" or "as soon as one promise fulfil or all reject". @domenic proposed to use the term `race()` to remove the ambiguity.

However, as @wasabiz pointed, adding `race()` seems to contradict the goal to have a minimalistic core. This method isn't a commonly used name and the behaviour is pretty simple to implement as needed. If the entire story around `some()`, `any()`, `race()` is not clear yet it seems that the best thing to do would be to not include this feature and see how things go. At least, in a Web API context, I would propose that but maybe in ES things are a bit different.

Obviously, if there are clear data showing that `race()` fulfil a common use case, all of that should be ignored ;)

**Comment by annevk** [comment]
I don't feel strongly. DOM only ever had an example for every (now all). @erights?

**Comment by erights** [comment]
First, on the naming, I feel strongly that "race" is a good name and "any" and "some" are bad names. I can into that if necessary, but I think we've been over that enough.

Second, as to whether to include this functionality, under whatever name, in promises-unwrapping: I see this as in the same boat as .catch and .done. All could be omitted at this stage. I believe all of these will be present soon regardless. We've decided to keep .catch in at this stage and not .done, because there was controversy about the need for .done's functionality but not .catch's.

If the only controversy about .race is the name, I propose we keep it in named "race". If there is actual significant controversy about whether its functionality is needed[1], then I propose we postpone .race to a later stage.

[1] Having written a lot of asynchronous code in this paradigm, I am confident the functionality of .race is needed -- indeed more confident than I am of .done or .catch, though less confident than for .all. For example, http://research.google.com/pubs/pub40673.html makes criticial use of .race and .all, but does not even mention .done or .catch. Please take a look and you'll see this isn't a one-off but for highly reusable reasons.

**Comment by erights** [comment]
> Obviously, if there are clear data showing that race() fulfil a common use case, all of that should be ignored ;)

Rereading the original message, especially the above quote, I'm closing this. I consider my experience and the patterns I document in that paper to be clear data that .race fulfills a common use case. But thanks for raising this.
