### ISSUE TITLE
Default handler arguments on .then

### ISSUE THREAD

**Issue by rossberg** [domenic/promises-unwrapping#66]
Why do the handler arguments to the .then method default to the internal resolve/reject functions? That seems rather weird, since the respective one will now be called twice, the second time with undefined as the (redundant) resolution value/reason.

Why don't the handlers simply default to empty functions?

Alternatively, the spec could make sure to simply not queue omitted handlers.

**Comment by domenic** [comment]
Right, I believe this arose evolutionarily. Your original code did not account for non-callable `onFulfilled` or `onRejected` arguments, so my first fix was to pass in a "fallback handler" and, if the relevant handler was non-callable, use that. (Some kind of handler is necessary to make `fulfilledPromise.then(undefined, e => console.error(e)).then(v => console.log(e))` work; otherwise the intermediate promise stays pending forever.)

This got kind of ugly ... there was something else that needed to be added to make it work ... I was able to simplify it a lot by using the current approach, and all the test still passed, so I leaned toward spec simplicity over realistic fidelity to how an implementation would work/optimize.

But, I can imagine that I leaned too far in that direction. If I thought about the problem a bit harder, I'd probably be able to come up with a solution that doesn't complicate things too much. Perhaps the one suggested in your last sentence.

If you want to dig into it yourself, you can try modifying the relevant portions of testable-implementation.js, running `npm install` and then `npm test` with Node 0.11.7+ installed. Or you can tell me what you think the modifications would be (either to that code or in spec language) and I can try them myself.
