### ISSUE TITLE
Update to align with ES6 spec text

### ISSUE THREAD

**Issue by domenic** [domenic/promises-unwrapping#91]
@allenwb made several editorial changes (all for the better) that we should roll into this repo.

My plan is to do one commit integrating those changes, then proceed by adding commits that address remaining issues, e.g. #89, or typos in the prose, or the changes stemming from the recent TC39 meeting. While I do so, I'll file bugs in the ECMAScript bug tracker linking to the diffs to make it easier for @allenwb.

I think this is a reasonable way to offload most of the relevant work to me and let @allenwb focus on ES draft integration---the majority of which was done already via the initial port, so that most of the rest will likely be simple diffs. What do you think, Allen?

**Comment by allenwb** [comment]
sounds good.

**Comment by stefanpenner** [comment]
:+1:

**Comment by cscott** [comment]
FWIW, I've filed the following bugs against the current version of the spec:

https://bugs.ecmascript.org/show_bug.cgi?id=2513
Promise.prototype.then uses constructor, not [[PromiseConstructor]]

https://bugs.ecmascript.org/show_bug.cgi?id=2514
Promise.all() and Promise.race() can't take a "promise for an array"

https://bugs.ecmascript.org/show_bug.cgi?id=2515
Promise.race() hangs forever if array is length 0

https://bugs.ecmascript.org/show_bug.cgi?id=2517
"SameAs" in CreatePromiseCapabilityRecord

Of these, I think 2513 and 2517 are simple editorial issues which @allenwb can take care of, while 2514 and 2515 are more weighty "let's think about the API" issues which are maybe more in @domenic's area.

I am, I guess, now maintaining the Promise implementation in `es6-shim` ( https://github.com/paulmillr/es6-shim/issues/170 ) so I'd be grateful for periodic reminders when the Promise-related bits of the spec change.

**Comment by domenic** [comment]
@cscott the time for substantial changes as in your 2514 and 2515 have passed; we are not planning to make any such further changes.

As for where to file bugs, I hope that after I update this spec to track Allen's changes, we can continue using this as an issue tracker to hash out discussions before presenting final results to Allen as diffs, per the above post. I will certainly defer to him though if he prefers to use the ES bug tracker from now on, plus using the GitHub tracker for the issues that are already open there.

**Comment by cscott** [comment]
I can take it or leave it on 2514, but I strongly feel that writing a resource leak into the spec for 2515 is a very bad idea.  At the very least you should punt and say that the results of Promise.race([]) are 'implementation defined', so that browser authors can decide whether to leak forever or emit a message on console or throw a TypeError or otherwise be friendly to their developers.  But I'll take up that horse in https://github.com/domenic/promises-unwrapping/issues/75, I guess.

I will suggest that if you want to use the github tracker instead of the ES one, you need to add a note to http://wiki.ecmascript.org/doku.php?id=harmony:specification_drafts so that others who might be implementing the spec know where to discuss Promise-related issues.

**Comment by domenic** [comment]
FYI after returning from a conference this is now first on my list of priorities and will be my after-work work for the next couple of days. Expect an initial commit aligning with Allen's spec changes soon.

**Comment by domenic** [comment]
Done in e310e4f76a96a39bb141e749990d0cb5141e23c0; subsequent commits are deltas against the ES6 spec draft. Will file bugs for them once things have settled down.
