### ISSUE TITLE
Throw error if Promise.all counter exceeds Number.MAX_SAFE_INTEGER?

### ISSUE THREAD

**Issue by anba** [domenic/promises-unwrapping#92]
`Promise.all` should throw (or reject?) if the counter exceeds some limit. It's unlikely engines will implement the specification as is, because that'd require to use a decimal type, cf. [definition for mathematical addition](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-algorithm-conventions).

Test case for this scenario:

``` javascript
class BrokenPromise extends Promise {
  // Empty method to avoid OOM
  then() { }
}

function* g() {
  let value = new BrokenPromise(() => {});
  while (1) yield value;
}

BrokenPromise.all(g());
```

**Comment by domenic** [comment]
What does the spec say for existing variadic methods like Math.max Math.hypot etc.?

**Comment by anba** [comment]
> What does the spec say for existing variadic methods like Math.max Math.hypot etc.?

Function arguments are internally represented as [Lists](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-list-and-record-specification-type), which do not have any length restriction. So just based on the specification it's possible to call a function with whatever number of arguments you like. In practice implementations will throw some kind of error when a certain argument limit was exceeded.

**Comment by domenic** [comment]
In that case I don't think it's the specification's job to place such limits...

**Comment by stefanpenner** [comment]
well, abit off topic interestingly `arguments` has platform specific limits.

**Comment by anba** [comment]
Placing a limit in the spec has the advantage implementations won't need to define their own behaviour. For example the reference implementation will just [refuse to update the counter](https://github.com/domenic/promises-unwrapping/blob/a3a8a88c9091a009be7d2320cf0e590317db5956/reference-implementation/lib/testable-implementation.js#L376), whereas WebKit's implementation simply performs [an integer overflow](https://github.com/WebKit/webkit/blob/9c6e0638a05087c2e1361cec834d9bbb06bdc33e/Source/JavaScriptCore/runtime/JSPromiseConstructor.cpp#L427).

**Comment by domenic** [comment]
I guess I would like @allenwb's guidance in that case :)

**Comment by allenwb** [comment]
Unless explicitly stated otherwise, all arithmetic operations in the ES spec. are considered to compute exact mathematical results on mathematical real numbers.  If an implementation must impose  limitation it should throw an exception when it is exceeded.  

In general, the ECMAScript specification does not try to define explicit minimum or limits on things like this.  Any such values would be arbitrary and unlikely to the reflect  actual pragmatic implementation consideration.   We expect that any such limitations imposed an implementation will be large enough to never become  interoperability issues.  Throwing as a mode of failure is alway preferred over silent misbehavior.

In this case, it would seem reasonable for an implementation to use a 32-bit counter but that isn't something that we would want specify.

**Comment by domenic** [comment]
OK, cool. @anba I think this is an interesting topic and maybe one worth broaching on es-discuss, but it's not promise-specific, so I'll close this issue without any action item for the promise spec.

One route forward might be to ask for text to be added to the language spec explaining in more detail what @allenwb went over above. Right now it seems kind of implicit in the definitions of Lists and arithmetic and so on, without giving the reasoning behind it, so it could be helpful.
