### ISSUE TITLE
thisArgument of new Promise resolver can be more useful

### ISSUE THREAD

**Issue by smcmurray** [domenic/promises-unwrapping#97]
The [resolver spec](https://github.com/domenic/promises-unwrapping#promise--resolver-) at line 13 mandates that the resolver has to be called with the _thisArgument_ undefined.

Would it be more useful to set the _thisArgument_ to _promise_?

**Comment by juandopazo** [comment]
We've discussed this in https://github.com/promises-aplus/constructor-spec/issues/23, and I think the consensus was to keep it `undefined` for consistency with `then`.

**Comment by domenic** [comment]
Hi @smcmurray! This spec is finalized, and no further API changes will be made to it beyond those necessary to align with the January TC39 consensus. Since the APIs are already shipping in browsers, we couldn't really make such changes even if we tried. So thanks for your interest, but we won't be able to do anything about it.

Anyway, the issue is that the resolver argument is not a method, but instead a function, and as such it should be called as a function, and not invoked as a method.
